defaults:
  taskcluster:
    scopeBase: '...'
    clientIdBase: '...'
    credentialsExpire: '...'
    allowedIps:
      - "0.0.0.0/0"
      - "0:0:0:0:0:0:0:0/0"
    credentials:
      clientId: '...'
      accessToken: '...'

  server:
    publicUrl: '...'
    port: 443
    env: production
    forceSSL: true
    trustProxy: false
